services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-portfolio
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer-portfolio
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - app-network

  next:
    build:
      context: ./next
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    container_name: next-portfolio
    environment:
      - STRAPI_API_URL=http://strapi-portfolio:1337/api
      - STRAPI_API_TOKEN=${STRAPI_API_TOKEN}
    ports:
      - "3000:3000"
    volumes:
      - ./next:/app
      - /app/node_modules
    networks:
      - app-network
  
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    container_name: strapi-portfolio
    environment:
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_NAME}
      - PUBLIC_URL=http://${DOMAIN_NAME}/strapi
    ports:
      - 1337:1337
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
